import type { Metadata } from "next";
import "./globals.css";
import { Toaster } from "sonner";
import { SidebarProvider, SidebarTrigger } from "../components/ui/sidebar";
import { AppSidebar } from "../components/app-sidebar";

export const metadata: Metadata = {
  title: "Albertonic",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="h-full">
      <body className="h-full antialiased">
        <div className="flex h-full overflow-y-scroll">
          <SidebarProvider>
            <AppSidebar />
            <main className="mx-2 h-full w-full">
              <SidebarTrigger />
              {children}
            </main>
          </SidebarProvider>
        </div>
        <Toaster />
      </body>
    </html>
  );
}
