import type { Metadata } from "next";
import "./globals.css";
import Sidenav from "../components/Sidenav";
import { Toaster } from "sonner";

export const metadata: Metadata = {
  title: "Albertonic",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="h-full">
      <body className="h-full antialiased">
        <div className="flex h-full overflow-y-scroll">
          <Sidenav />
          <div className="mx-2 h-full w-full">{children}</div>
        </div>
        <Toaster />
      </body>
    </html>
  );
}
